# Importing all required libraries

In [29]:
import pandas as pd
import numpy as np

# Loaded date file through pandas

In [30]:
Data = pd.read_excel("cleaned_project_file.xlsx")

# Viewing Data and Datatype

In [31]:
Data

,Account_Number,Patient_Name,DOB,DOS,Claim_Submission_Date,Insurance_Company,Rendering_Provider,Facility,Department,blan,...,Denial_Reason,Denial_Category,Aging_Bucket,Appeal_Status,Appeal_Level,Payment_Method,Place_of_Service,Days_to_Bill,Days_to_Payment,Claim_ID
0,ACC101437,Patient 844,1970-06-11,2025-08-02,2025-08-12,Ambetter,Dr. Miller,Prime Care,Orthopedics,80050.0,...,NaN,NaN,61-90,Submitted,Level 3,ERA,23,28,99,CLM201437
1,ACC100749,Patient 2543,2012-07-17,2025-06-21,2025-07-05,Humana,Dr. Patel,Westside Clinic,Cardiology,71020.0,...,Duplicate Claim,Documentation,61-90,Not Started,NaN,EFT,21,1,34,CLM200749
2,ACC104113,Patient 3117,1986-07-13,2025-09-08,2025-09-14,Humana,Dr. Brown,East Medical Center,Orthopedics,99215.0,...,NaN,NaN,120+,Not Started,Level 3,EFT,23,9,44,CLM204113
3,ACC101449,Patient 2448,2017-05-24,2024-01-08,2024-01-22,Blue Cross,Dr. Patel,Prime Care,Orthopedics,99213.0,...,NaN,NaN,31-60,Resolved,Level 1,Check,21,53,17,CLM201449
4,ACC103892,Patient 928,1967-07-07,2024-12-16,2024-12-30,Molina,Dr. Miller,East Medical Center,Internal Medicine,99215.0,...,Claim lacks information,Documentation,120+,Resolved,Level 3,NaN,11,31,105,CLM203892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5675,ACC103773,Patient 2512,1973-01-18,2025-09-11,2025-09-14,Molina,Dr. Wilson,Sunrise Health,Cardiology,99214.0,...,Non-covered charge,Other,61-90,Submitted,NaN,EFT,23,27,45,CLM203773
5676,ACC105192,Patient 735,1969-02-20,2025-03-01,2025-03-03,Blue Cross,Dr. Patel,Downtown Hospital,Internal Medicine,99215.0,...,Claim lacks information,Documentation,31-60,Submitted,NaN,EFT,11,17,59,CLM205192
5677,ACC105227,Patient 44,2004-12-19,2024-07-28,2024-08-05,Tricare,Dr. Johnson,Prime Care,Cardiology,71020.0,...,NaN,NaN,0-30,Submitted,Level 1,NaN,23,20,75,CLM205227
5678,ACC105391,Patient 40,1999-05-23,2025-04-17,2025-04-22,Ambetter,Dr. Johnson,Westside Clinic,Orthopedics,99214.0,...,NaN,NaN,31-60,Not Started,Level 2,NaN,21,31,105,CLM205391
5679,ACC100861,Patient 541,2010-07-21,2025-05-10,2025-05-23,Tricare,Dr. Miller,North Clinic,Neurology,80050.0,...,NaN,NaN,31-60,Resolved,NaN,ERA,21,41,87,CLM200861

In [32]:
Data.head(5)

,Account_Number,Patient_Name,DOB,DOS,Claim_Submission_Date,Insurance_Company,Rendering_Provider,Facility,Department,blan,...,Denial_Reason,Denial_Category,Aging_Bucket,Appeal_Status,Appeal_Level,Payment_Method,Place_of_Service,Days_to_Bill,Days_to_Payment,Claim_ID
0,ACC101437,Patient 844,1970-06-11,2025-08-02,2025-08-12,Ambetter,Dr. Miller,Prime Care,Orthopedics,80050.0,...,NaN,NaN,61-90,Submitted,Level 3,ERA,23,28,99,CLM201437
1,ACC100749,Patient 2543,2012-07-17,2025-06-21,2025-07-05,Humana,Dr. Patel,Westside Clinic,Cardiology,71020.0,...,Duplicate Claim,Documentation,61-90,Not Started,NaN,EFT,21,1,34,CLM200749
2,ACC104113,Patient 3117,1986-07-13,2025-09-08,2025-09-14,Humana,Dr. Brown,East Medical Center,Orthopedics,99215.0,...,NaN,NaN,120+,Not Started,Level 3,EFT,23,9,44,CLM204113
3,ACC101449,Patient 2448,2017-05-24,2024-01-08,2024-01-22,Blue Cross,Dr. Patel,Prime Care,Orthopedics,99213.0,...,NaN,NaN,31-60,Resolved,Level 1,Check,21,53,17,CLM201449
4,ACC103892,Patient 928,1967-07-07,2024-12-16,2024-12-30,Molina,Dr. Miller,East Medical Center,Internal Medicine,99215.0,...,Claim lacks information,Documentation,120+,Resolved,Level 3,NaN,11,31,105,CLM203892

In [33]:
Data.shape

(5680, 28)

In [34]:
Data.columns

Index(['Account_Number', 'Patient_Name', 'DOB', 'DOS', 'Claim_Submission_Date',
       'Insurance_Company', 'Rendering_Provider', 'Facility', 'Department',
       'blan', 'ICD10_Code', 'Billed_Amount', 'Allowed_Amount', 'Paid_Amount',
       'Patient_Responsibility', 'Remaining_Balance', 'Claim_Status',
       'Denial_Code', 'Denial_Reason', 'Denial_Category', 'Aging_Bucket',
       'Appeal_Status', 'Appeal_Level', 'Payment_Method', 'Place_of_Service',
       'Days_to_Bill', 'Days_to_Payment', 'Claim_ID'],
      dtype='object')

In [35]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5680 entries, 0 to 5679
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Account_Number          5680 non-null   object
 1   Patient_Name            5680 non-null   object
 2   DOB                     5680 non-null   datetime64[ns]
 3   DOS                     5680 non-null   datetime64[ns]
 4   Claim_Submission_Date   5680 non-null   datetime64[ns]
 5   Insurance_Company       5595 non-null   object
 6   Rendering_Provider      5595 non-null   object
 7   Facility                5680 non-null   object
 8   Department              5680 non-null   object
 9   blan                    5595 non-null   float64
 10  ICD10_Code              5680 non-null   object
 11  Billed_Amount           5680 non-null   object
 12  Allowed_Amount          5680 non-null   float64
 13  Paid_Amount             5595 non-null   float64
 14  Patient_Responsibility  5680 non-null   float64
 15  Remaining_Balance       5595 non-null   float64
 16  Claim_Status            5680 non-null   object
 17  Denial_Code             2705 non-null   object
 18  Denial_Reason           2715 non-null   object
 19  Denial_Category         2752 non-null   object
 20  Aging_Bucket            5680 non-null   object
 21  Appeal_Status           5595 non-null   object
 22  Appeal_Level            4219 non-null   object
 23  Payment_Method          4275 non-null   object
 24  Place_of_Service        5680 non-null   int64
 25  Days_to_Bill            5680 non-null   int64
 26  Days_to_Payment         5680 non-null   object
 27  Claim_ID                5680 non-null   object
dtypes: datetime64[ns](3), float64(5), int64(2), object(18)
memory usage: 1.2+ MB

# Cleaning Data

In [37]:
Data.duplicated().sum()

143

# Removed Duplicate Date

In [38]:
Data = Data.drop_duplicates()

In [39]:
Data.duplicated().sum()

0

# Deleting Extra space and in one format

In [44]:
Data['Claim_Status'] = Data['Claim_Status'].str.strip().str.title()

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\3338607677.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Claim_Status'] = Data['Claim_Status'].str.strip().str.title()

In [45]:
Data['Insurance_Company'] = Data['Insurance_Company'].str.strip().str.title()

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\3882674963.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Insurance_Company'] = Data['Insurance_Company'].str.strip().str.title()

# Changing Billed amt datatype

In [46]:
Data['Billed_Amount'] = pd.to_numeric(Data['Billed_Amount'], errors='coerce')

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\3778853039.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Billed_Amount'] = pd.to_numeric(Data['Billed_Amount'], errors='coerce')

In [48]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5537 entries, 0 to 5679
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Account_Number          5537 non-null   object
 1   Patient_Name            5537 non-null   object
 2   DOB                     5537 non-null   datetime64[ns]
 3   DOS                     5537 non-null   datetime64[ns]
 4   Claim_Submission_Date   5537 non-null   datetime64[ns]
 5   Insurance_Company       5452 non-null   object
 6   Rendering_Provider      5452 non-null   object
 7   Facility                5537 non-null   object
 8   Department              5537 non-null   object
 9   blan                    5452 non-null   float64
 10  ICD10_Code              5537 non-null   object
 11  Billed_Amount           5518 non-null   float64
 12  Allowed_Amount          5537 non-null   float64
 13  Paid_Amount             5452 non-null   float64
 14  Patient_Responsibility  5537 non-null   float64
 15  Remaining_Balance       5452 non-null   float64
 16  Claim_Status            5537 non-null   object
 17  Denial_Code             2638 non-null   object
 18  Denial_Reason           2647 non-null   object
 19  Denial_Category         2684 non-null   object
 20  Aging_Bucket            5537 non-null   object
 21  Appeal_Status           5452 non-null   object
 22  Appeal_Level            4118 non-null   object
 23  Payment_Method          4168 non-null   object
 24  Place_of_Service        5537 non-null   int64
 25  Days_to_Bill            5537 non-null   int64
 26  Days_to_Payment         5537 non-null   object
 27  Claim_ID                5537 non-null   object
dtypes: datetime64[ns](3), float64(6), int64(2), object(17)
memory usage: 1.2+ MB

# Filing and deleting Null values

In [49]:
Data.isnull().sum()

Account_Number               0
Patient_Name                 0
DOB                          0
DOS                          0
Claim_Submission_Date        0
Insurance_Company           85
Rendering_Provider          85
Facility                     0
Department                   0
blan                        85
ICD10_Code                   0
Billed_Amount               19
Allowed_Amount               0
Paid_Amount                 85
Patient_Responsibility       0
Remaining_Balance           85
Claim_Status                 0
Denial_Code               2899
Denial_Reason             2890
Denial_Category           2853
Aging_Bucket                 0
Appeal_Status               85
Appeal_Level              1419
Payment_Method            1369
Place_of_Service             0
Days_to_Bill                 0
Days_to_Payment              0
Claim_ID                     0
dtype: int64

In [50]:
Data['Insurance_Company'] = Data['Insurance_Company'].fillna('Unknown')

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\4252670063.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Insurance_Company'] = Data['Insurance_Company'].fillna('Unknown')

In [51]:
Data['Rendering_Provider'] = Data['Rendering_Provider'].fillna('Unknown provider')

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\1968087339.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Rendering_Provider'] = Data['Rendering_Provider'].fillna('Unknown provider')

In [54]:
Data['blan'] = Data['blan'].fillna('Na')

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\2487858095.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['blan'] = Data['blan'].fillna('Na')

In [55]:
Data['Paid_Amount'] = Data['Paid_Amount'].fillna('0')

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\4249953477.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Paid_Amount'] = Data['Paid_Amount'].fillna('0')

In [56]:
Data['Remaining_Balance'] = Data['Remaining_Balance'].fillna('0')

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\2787137643.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Remaining_Balance'] = Data['Remaining_Balance'].fillna('0')

In [57]:
Data['Appeal_Status'] = Data['Appeal_Status'].fillna('Not Started')

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\3220869028.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Appeal_Status'] = Data['Appeal_Status'].fillna('Not Started')

In [58]:
Data['Billed_Amount'] = Data['Billed_Amount'].fillna(Data['Billed_Amount'].median())

C:\Users\nurud\AppData\Local\Temp\ipykernel_16544\1195556320.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Billed_Amount'] = Data['Billed_Amount'].fillna(Data['Billed_Amount'].median())

In [59]:
Data.isnull().sum()

Account_Number               0
Patient_Name                 0
DOB                          0
DOS                          0
Claim_Submission_Date        0
Insurance_Company            0
Rendering_Provider           0
Facility                     0
Department                   0
blan                         0
ICD10_Code                   0
Billed_Amount                0
Allowed_Amount               0
Paid_Amount                  0
Patient_Responsibility       0
Remaining_Balance            0
Claim_Status                 0
Denial_Code               2899
Denial_Reason             2890
Denial_Category           2853
Aging_Bucket                 0
Appeal_Status                0
Appeal_Level              1419
Payment_Method            1369
Place_of_Service             0
Days_to_Bill                 0
Days_to_Payment              0
Claim_ID                     0
dtype: int64

# Deleting unwanted column

In [60]:
Data.columns

Index(['Account_Number', 'Patient_Name', 'DOB', 'DOS', 'Claim_Submission_Date',
       'Insurance_Company', 'Rendering_Provider', 'Facility', 'Department',
       'blan', 'ICD10_Code', 'Billed_Amount', 'Allowed_Amount', 'Paid_Amount',
       'Patient_Responsibility', 'Remaining_Balance', 'Claim_Status',
       'Denial_Code', 'Denial_Reason', 'Denial_Category', 'Aging_Bucket',
       'Appeal_Status', 'Appeal_Level', 'Payment_Method', 'Place_of_Service',
       'Days_to_Bill', 'Days_to_Payment', 'Claim_ID'],
      dtype='object')

In [61]:
Data.Appeal_Level

0       Level 3
1           NaN
2       Level 3
3       Level 1
4       Level 3
         ...
5675        NaN
5676        NaN
5677    Level 1
5678    Level 2
5679        NaN
Name: Appeal_Level, Length: 5537, dtype: object

In [63]:
Data = Data.drop(columns=['Appeal_Level','ICD10_Code'])

# Changing Name

In [64]:
Data = Data.rename(columns={'blan': 'CPT'})

In [65]:
Data.columns

Index(['Account_Number', 'Patient_Name', 'DOB', 'DOS', 'Claim_Submission_Date',
       'Insurance_Company', 'Rendering_Provider', 'Facility', 'Department',
       'CPT', 'Billed_Amount', 'Allowed_Amount', 'Paid_Amount',
       'Patient_Responsibility', 'Remaining_Balance', 'Claim_Status',
       'Denial_Code', 'Denial_Reason', 'Denial_Category', 'Aging_Bucket',
       'Appeal_Status', 'Payment_Method', 'Place_of_Service', 'Days_to_Bill',
       'Days_to_Payment', 'Claim_ID'],
      dtype='object')

In [66]:
Data = Data.drop(columns=['Allowed_Amount'])

# Creating Year and Month column for comparison

In [67]:
Data['DOS'] = pd.to_datetime(Data['DOS'])

In [70]:
Data['DOS_Year'] = Data['DOS'].dt.year

In [72]:
Data['DOS_Month'] = Data['DOS'].dt.month_name()

# Creating Denial and paid flags for easy calculation

In [74]:
Data['Claim_Status'].value_counts()

Claim_Status
Denied      2691
Paid        2005
Adjusted     841
Name: count, dtype: int64

In [75]:
Data['Denial_Flag'] = np.where(Data['Claim_Status'] == 'Denied',1,0)

In [76]:
Data['Paid_Flag'] = np.where(Data['Claim_Status'] == 'Paid',1,0)

In [77]:
Data['Denial_Flag']

0       0
1       1
2       0
3       0
4       1
       ..
5675    1
5676    1
5677    0
5678    0
5679    0
Name: Denial_Flag, Length: 5537, dtype: int32

# Checking Insight and Trend

In [79]:
Data['Claim_Status'].value_counts()

Claim_Status
Denied      2691
Paid        2005
Adjusted     841
Name: count, dtype: int64

In [ ]:
Data['Claim_Status'].value_counts (normalize=True) * 100

Claim_Status
Denied      48.600325
Paid        36.210945
Adjusted    15.188730
Name: proportion, dtype: float64

# Checking Denial Trend

In [82]:
Data['Denial_Code'].value_counts().head(10)

Denial_Code
CO18                     373
CO16                     304
PR27                     247
CO109                    181
PR1                      177
CO22                     153
N382                     138
Provider Not Enrolled    138
CO45                     121
CO96                     116
Name: count, dtype: int64

In [83]:
Data.groupby('Insurance_Company')['Denial_Flag'].sum().sort_values(ascending=False)

Insurance_Company
Ambetter             305
Molina               303
Medicaid             295
United Healthcare    272
Aetna                255
Cigna                254
Humana               253
Tricare              244
Blue Cross           243
Medicare             230
Unknown               37
Name: Denial_Flag, dtype: int32

In [84]:
Data.groupby('Insurance_Company')['Paid_Flag'].sum().sort_values(ascending=False)

Insurance_Company
Molina               209
Aetna                207
Cigna                207
Medicare             202
Ambetter             201
Blue Cross           196
Tricare              195
Medicaid             193
Humana               186
United Healthcare    180
Unknown               29
Name: Paid_Flag, dtype: int32

In [87]:
Data.groupby('Insurance_Company')['Billed_Amount'].sum().sort_values(ascending=False)

Insurance_Company
Molina               783212.07
Ambetter             750964.00
Medicaid             718481.32
Aetna                699926.15
Blue Cross           699485.77
Cigna                698953.13
United Healthcare    685487.20
Medicare             684113.09
Humana               675907.13
Tricare              663862.50
Unknown              111785.79
Name: Billed_Amount, dtype: float64

In [85]:
Data.groupby('Rendering_Provider')['Denial_Flag'].sum().sort_values(ascending=False)

Rendering_Provider
Dr. Wilson          332
Dr. Patel           329
Dr. Davis           274
Dr. Taylor          261
Dr. Johnson         259
Dr. Smith           248
Dr. Miller          246
Dr. Williams        245
Dr. Brown           237
Dr. Anderson        222
Unknown provider     38
Name: Denial_Flag, dtype: int32

In [86]:
Data.groupby('Rendering_Provider')['Billed_Amount'].sum().sort_values(ascending=False)

Rendering_Provider
Dr. Wilson          818157.38
Dr. Patel           779259.26
Dr. Miller          730699.17
Dr. Johnson         727709.91
Dr. Davis           711649.05
Dr. Williams        700056.45
Dr. Brown           677824.87
Dr. Smith           657470.72
Dr. Taylor          634555.69
Dr. Anderson        624204.01
Unknown provider    110591.64
Name: Billed_Amount, dtype: float64

# Exporting File to Excel

In [89]:
Data.to_excel ("Complete_Project_File.xlsx" , index= False)